name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t tests-image .

      - name: Run Docker container and execute tests
        run: |
          docker run --rm --name Tests tests-image pytest --maxfail=1 --disable-warnings
