name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t tests-image .

      - name: Start Docker container in detached mode
        run: |
          docker run -d --name Tests -p 8000:8000 tests-image

      - name: Wait for server to start
        run: |
          echo "Waiting for the server to start..."
          sleep 10  # Adjust if the server takes longer to start

      - name: Run tests
        run: docker exec Tests pytest --maxfail=1 --disable-warnings

      - name: Stop and remove Docker container
        if: always()
        run: docker container rm -f Tests
